### ISSUE TITLE
A couple of less breaking things.

### ISSUE THREAD

**Issue by Atronosthelast** [knighty/fimfiction-issues#127] opened 2017-06-19 05:32 UTC
As the title says, these are just little things that I see time to time that annoy me.

Firstly, when using the site on my PC there is a large gap between the cover art and the description 
![untitled](https://user-images.githubusercontent.com/29531585/27270804-67a63ec0-54b0-11e7-98fc-742d15f82e01.png)
(I use a 32" TV for my PC which may be why this happens, but it didn't do this before the update)

Another issue I have is the notification/messages boxes not opening when I hover over them. This doesn't happen all the time, but when it does it can get fairly annoying. This may just be me, however.

**Comment by knighty** [comment] 2017-06-19 10:40
What version of Firefox are you on? I've seen a couple of people with that cover art issue.

**Comment by Atronosthelast** [comment] 2017-06-19 12:43
The latest possible version.

**Comment by knighty** [comment] 2017-06-19 12:46
Could you try it in an incognito tab to rule out extensions? Trying at 100% DPI might also be a good idea.

edit: Testing myself, it's DPI related.

**Comment by Atronosthelast** [comment] 2017-06-19 12:47
I can give it a try, hang on.

**Comment by Atronosthelast** [comment] 2017-06-19 12:50
![untitled](https://user-images.githubusercontent.com/29531585/27285928-ddf3e356-54ed-11e7-9ac3-8e2d9d300186.png)
nope

**Comment by knighty** [comment] 2017-06-19 13:45
From my testing this looks like a firefox bug. If you're zoomed in at all (whether manually or due to DPI settings) it breaks it. I haven't been able to figure out a fix.

**Comment by Atronosthelast** [comment] 2017-06-19 13:46
Ah, okay. Well, thanks for trying anyways ^-^

**Comment by knighty** [comment] 2017-06-19 13:48
Spoke too soon, found the cause and fixed it. Will close this when the change gets deployed.

**Comment by Atronosthelast** [comment] 2017-06-19 13:50
Oh, haha. Welp, thanks again :P

**Comment by knighty** [comment] 2017-06-20 08:07
This should be in now.

**Closed as completed by knighty** 2017-06-20 08:07 UTC
