### ISSUE TITLE
Formatting Options Overstep Author's Box Boundaries on Chapter Edit Page

### ISSUE THREAD

**Issue by NavelColt** [knighty/fimfiction-issues#24] opened 2017-06-07 16:01 UTC
Upon editing a chapter, the formatting buttons above the author's box trail right off the box bar.

Using Chrome on Windows 10 OS.

![untitled](https://user-images.githubusercontent.com/29257885/26888318-abb03a58-4b78-11e7-825c-c39c72d02a04.png)

**Comment by xaquseg** [comment] 2017-06-07 16:32
Duplicate of #9

**Closed as completed by xaquseg** 2017-06-07 16:32 UTC
Labels: duplicate
